require './challenges/find_duplicates'
require './challenges/appears_most_times'
require './challenges/hash_table'
require './challenges/prime_numbers'
require './challenges/prime_prime'
require './challenges/more_practice'
require './challenges/insertion_sort1'
require './challenges/insertion_sort_itself'
